### Create new employee

POST http://localhost:4000/emp/emp
Content-Type: application/json

{
    "name":"sri",
    "email":"sri@email.com",
    "designation":"HR",
    "companyName":"Google"
}

### Read all employees
GET http://localhost:4000/emp/emp




### Update employee
PUT http://localhost:4000/emp/emp/69ca26b97e8913c1b936ba7b
Content-Type: application/json

{
    "name":"nishika",
    "email":"nishika@gmail.com",
    "designation":"Manager",
    "companyName":"Amazon"
}

### delete employee
DELETE http://localhost:4000/emp/emp/